name: bisescratch
recipe: drupal8
config:
  webroot: web
  php: '7.1'
services:
  appserver:
    run:
      - "mkdir -p ~/.drush/site-aliases"
      - "ln -sf /app/drush/bise.aliases.drushrc.php ~/.drush/site-aliases/bise.drushrc.php"
